name: capture_atcoder_rate

on:
  schedule:
    - cron: "0 1 1-31 * *"

jobs:
  capture:
    name: Build production
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          ref: remotes/origin/master

      - name: Setup git
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config --local user.name GitHubActions
          git remote set-url origin https://wawawatataru:${ACCESS_TOKEN}@github.com/wawawatataru/atcoder_ogp.git

      - name: Git pull
        run: |
          git checkout -b master origin/master
          git pull origin master

      - name: Build Docker
        run: |
          docker build -t atcoder_ogp .
          docker run -d -p 80:80 --name capture  atcoder_ogp
          docker cp capture:/home/rotelstift/python_capture/docs/image/screenshot.png ./docs/image/screenshot.png

      - name: Git commit
        run: |
          git add -A
          DIFF=`git diff --cached --numstat | wc -l`
          if [ $DIFF -eq 0 ]; then
            exit 0
          fi
          git commit -am 'GitHub Actions commit' --allow-empty

      - name: Git push
        run: |
          git pull origin master
          git push origin master
